import pathlib,subprocess,json,hashlib,io
repo=pathlib.Path('D:/Projects/朝花夕拾');worker=pathlib.Path('C:/Users/hetia/.codex/worktrees/aed5/朝花夕拾');commit='4243325c3acf84ad828b8e1ddd84742ca594b94f';base='3fb6f3ae0b52c22cf02821f4ca1b04f650de82dd';g='D:/Git/cmd/git.exe';rel='docs/superpowers/verification/evidence/';h='redis-binary-p2-c5ecaf36b3e64182a159e583992e0fa0-worker-handoff';manifest=worker/rel/h/'manifest.json';m=json.loads(manifest.read_bytes());assert m['passed'] is False and m['overall']=='P2_PARTIAL';assert hashlib.sha256(manifest.read_bytes()).hexdigest()=='ce81bf0db2b4bd669a48f76b95e6227fd271b8a2076630af8fa5a6f705120551'
for row in m['files']:
 p=worker/row['path'];assert not any(x.casefold() in ('.testagent','.git','.g10-verify-blobs.ps1') for x in p.parts);b=p.read_bytes();assert len(b)==row['length'] and hashlib.sha256(b).hexdigest()==row['sha256']
changed=subprocess.check_output([g,'diff','--name-only','-z',base,commit,'--','.',':(exclude).testagent',':(exclude).testagent/**',':(exclude)**/.testagent/**',':(exclude).g10-verify-blobs.ps1'],cwd=repo).decode().strip('\0').split('\0');sources={'test/com/datacube/update/'+x for x in ('PortableUpdateHelperTest.java','UpdateHelperProcess.java','UpdateHelperProcessTest.java')};report='docs/superpowers/verification/release-helper-timeout-worker-20261010.md';prefixes=[rel+x+'/' for x in m['roots']+[h]]
for path in changed:assert path in sources or path==report or any(path.startswith(x) for x in prefixes),path
p=subprocess.Popen([g,'cat-file','--batch'],cwd=repo,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE);raw,err=p.communicate(''.join(commit+':'+x+'\n' for x in changed).encode());assert p.returncode==0 and not err;s=io.BytesIO(raw);rows=[]
for path in changed:
 header=s.readline().decode().strip().split();assert len(header)==3 and header[1]=='blob';n=int(header[2]);b=s.read(n);assert s.read(1)==b'\n';actual=(worker/path).read_bytes();assert b==actual,path;rows.append(dict(path=path,length=n,sha256=hashlib.sha256(b).hexdigest()))
assert s.read()==b''
result=dict(passedForLocalIntegration=True,formalP2Passed=False,sourceCommit=m['sourceCommit'],evidenceCommit=commit,baseMain=base,gitBlobMatchesWorker=len(rows),handoffManifestSha256=hashlib.sha256(manifest.read_bytes()).hexdigest(),roots=m['roots'],files=rows,remaining='Fresh formal main P3 required before push/tag; retained linked failure is not reclassified')
out=repo/'build/owned-release-helper-fix-bb14f6bacde74718a89a5a36284a6eae/worker-commit-review.json';out.write_bytes(json.dumps(result,ensure_ascii=False,indent=2).encode());print(json.dumps(dict(changedPaths=len(rows),sourcePaths=len(sources),handoffFiles=len(m['files']),sha256=hashlib.sha256(out.read_bytes()).hexdigest())))
