package com.datacube.spi.schemadiff;

public enum ObjectType {
    TABLE, PRIMARY_KEY, UNIQUE_CONSTRAINT, FOREIGN_KEY, CHECK_CONSTRAINT,
    INDEX, SEQUENCE, VIEW, MATERIALIZED_VIEW, FUNCTION, PROCEDURE,
    TRIGGER, PACKAGE_SPEC, PACKAGE_BODY, TYPE
}
