package com.datacube.fx;
import com.datacube.config.SqlDraftCoordinator;
import java.time.*; import java.time.format.*; import java.util.UUID; import java.util.concurrent.CompletableFuture; import java.util.function.Consumer;
import javafx.application.Platform; import javafx.beans.value.ChangeListener; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.layout.*; import org.fxmisc.richtext.CodeArea;
final class SqlDraftEditorBinding implements AutoCloseable {
 static final String PRIVACY="SQL 草稿仅保存于本机，可能含敏感文本；保留7天，可关闭或清空。关闭草稿不停止原有 SQL 历史记录。";
 private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("HH:mm:ss").withZone(ZoneId.systemDefault()); private final SqlDraftCoordinator runtime; private final SqlDraftCoordinator.Handle handle; private final CodeArea editor; private final TextField schema; private final Consumer<SqlDraftEditorBinding> detached; private final Label status=new Label(),notice=new Label(); private final Button retry=new Button("重试保存"),toggle=new Button(),clear=new Button("清空草稿"); private final VBox root; private final ChangeListener<String> changes=(o,b,a)->edited(); private boolean closed,closing,priorEditable,priorSchemaDisabled,managementPending; private CompletableFuture<Boolean> closeAttempt;
 SqlDraftEditorBinding(SqlDraftCoordinator runtime,UUID id,Long savedAt,CodeArea editor,TextField schema,SqlDraftCoordinator.Source source,Consumer<SqlDraftEditorBinding> detached){this.runtime=runtime;this.editor=editor;this.schema=schema;this.detached=detached;status.setId("sql-draft-status");retry.setId("sql-draft-retry");toggle.setId("sql-draft-toggle");clear.setId("sql-draft-clear");Label privacy=new Label(PRIVACY);privacy.setWrapText(true);privacy.setId("sql-draft-privacy");notice.setWrapText(true);notice.setId("sql-draft-notice");root=new VBox(3,new FlowPane(8,4,status,retry,toggle,clear),notice,privacy);root.setId("sql-draft-protection");handle=runtime.attach(id,savedAt,source);try{editor.textProperty().addListener(changes);schema.textProperty().addListener(changes);retry.setOnAction(e->{if(!closing&&!closed){handle.retry();runtime.pulse();refresh();}});toggle.setOnAction(e->{if(!closing&&!closed&&!managementPending)manage(runtime.setEnabled(runtime.mode()!=SqlDraftCoordinator.Mode.ENABLED));});clear.setOnAction(e->{if(!closing&&!closed&&!managementPending&&confirm("清空草稿","清空仅删除本机可恢复草稿，不清空编辑器；之后的新修改仍会保存。是否继续？","清空"))manage(runtime.clear());});refresh();}catch(RuntimeException failure){close();throw failure;}}
 Node getNode(){return root;} boolean closing(){return closing||closed;} void edited(){if(!closed&&!closing){handle.edited();refresh();}}
 void refresh(){if(closed)return;var s=handle.status();String text=switch(s.mode()){case INITIALIZING->"草稿保护初始化中，尚未确认保存";case DISABLED->"草稿保护已关闭";case PAUSED->"本次已暂停，关闭设置未保存，下次启动可能恢复";case UNAVAILABLE->"草稿保护不可用，请检查本地目录后重启";case CLOSED->"草稿保护已停止";case ENABLED->{yield switch(s.saveStatus()){case EMPTY->"草稿保护已开启";case WAITING->"草稿待保存";case SAVING->"正在保存草稿";case SAVED->"草稿已保存于 "+TIME.format(Instant.ofEpochMilli(s.savedAt()));case FAILED->"草稿保存失败，最新修改尚未保存";};}};status.setText(text);boolean canRetry=s.mode()==SqlDraftCoordinator.Mode.ENABLED&&s.saveStatus()==SqlDraftCoordinator.SaveStatus.FAILED;retry.setVisible(canRetry);retry.setManaged(canRetry);retry.setDisable(closing);toggle.setText(s.mode()==SqlDraftCoordinator.Mode.ENABLED?"关闭草稿保护":"开启草稿保护");boolean unavailable=s.mode()==SqlDraftCoordinator.Mode.INITIALIZING||s.mode()==SqlDraftCoordinator.Mode.UNAVAILABLE||s.mode()==SqlDraftCoordinator.Mode.CLOSED;toggle.setDisable(closing||managementPending||unavailable);clear.setDisable(closing||managementPending||unavailable);notice.setVisible(!notice.getText().isEmpty());notice.setManaged(notice.isVisible());}
 private void manage(CompletableFuture<SqlDraftCoordinator.ManagementResult> op){managementPending=true;notice.setText("");refresh();op.whenComplete((r,f)->Platform.runLater(()->{if(closed)return;managementPending=false;if(f!=null||!r.succeeded())notice.setText("草稿操作未完成，已有可恢复草稿可能仍然保留。");refresh();}));}
 void freeze(){if(closing||closed)return;priorEditable=editor.isEditable();priorSchemaDisabled=schema.isDisable();closing=true;editor.setEditable(false);schema.setDisable(true);refresh();}
 CompletableFuture<Boolean> prepareClose(boolean mandatory){if(closeAttempt!=null)return closeAttempt.copy();freeze();var attempt=new CompletableFuture<Boolean>();closeAttempt=attempt;try{handle.flush().whenComplete((u,f)->{try{Platform.runLater(()->{if(closed){attempt.complete(false);return;}try{refresh();boolean allow=f==null||(!mandatory&&confirm("最新草稿未保存","最新修改尚未保存。取消关闭后可重试保存；放弃仅跳过本次保存，不删除已有草稿，也不关闭草稿保护。","放弃本次最新修改并关闭"));if(!allow)reopen();attempt.complete(allow);}catch(Throwable x){reopen();attempt.completeExceptionally(x);}});}catch(Throwable x){attempt.completeExceptionally(x);}});}catch(Throwable x){reopen();attempt.completeExceptionally(x);}return attempt.copy();}
 void reopen(){if(!closing||closed)return;closing=false;closeAttempt=null;editor.setEditable(priorEditable);schema.setDisable(priorSchemaDisabled);refresh();}
 private boolean confirm(String title,String message,String acceptText){ButtonType accept=new ButtonType(acceptText,ButtonBar.ButtonData.OTHER);Alert alert=new Alert(Alert.AlertType.CONFIRMATION,message,ButtonType.CANCEL,accept);alert.setTitle(title);alert.setHeaderText(null);if(editor.getScene()!=null&&editor.getScene().getWindow()!=null)alert.initOwner(editor.getScene().getWindow());return alert.showAndWait().orElse(ButtonType.CANCEL)==accept;}
 public void close(){if(closed)return;closed=true;editor.textProperty().removeListener(changes);schema.textProperty().removeListener(changes);handle.detach();detached.accept(this);}
}
